repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
        name: linting
        args: [--fix]
      - id: ruff
        name: import sorting
        args: [--select, I, --fix]
      - id: ruff-format
        name: formatting
        args: [--extend-ignore=C901]        