[tool.ruff]
line-length = 88
exclude = ["tests", ".venv"]
target-version = "py310"

[tool.ruff.lint]
select = [
  "S",
  "I",
  "RUF",
  "C90",
  "F",
  "N",
]
extend-select = [
  "UP",
]
ignore = ["F403", "F405"]

[tool.ruff.format]
quote-style = "double"

[tool.pytest.ini_options]
pythonpath = ["src"]